name: Publish and Release

on:
  push:
    tags: [ 'v*' ] # Push events to matching v*, i.e. v1.0, v20.15.10
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Clean Install dependencies
        run: yarn install
          
      - name: Run Unit tests
        run: yarn test
      
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
